### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jiang8125** [RYTong/emp-debugger#132]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [emp-debugger](https://github.com/RYTong/emp-debugger) package 0.11.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\jiang\AppData\Local\atom\app-1.23.3\resources\app\node_modules\text-buffer\lib\text-buffer.js:948

TypeError: Cannot read property 'length' of undefined
    at exports.extentForText (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/helpers.js:91:34)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:678:48)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:662:32
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:660:27)
    at TextBuffer.module.exports.TextBuffer.setText (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:599:25)
    at TextEditor.setText (~/AppData/Local/atom/app-1.23.3/resources/app/src/text-editor.js:1295:45)
    at TextEditorView.module.exports.TextEditorView.setText (/packages/emp-debugger/node_modules/atom-space-pen-views/lib/text-editor-view.js:56:25)
    at VerifyProjectView.module.exports.VerifyProjectView.refresh_show_view (/packages/emp-debugger/lib/debugger/emp_verify_project_view.coffee:65:19)
    at VerifyProjectView.module.exports.VerifyProjectView.show_view (/packages/emp-debugger/lib/debugger/emp_verify_project_view.coffee:62:6)
    at VerifyProjectView.module.exports.VerifyProjectView.toggle (/packages/emp-debugger/lib/debugger/emp_verify_project_view.coffee:53:8)
    at EmpSnippetsView.module.exports.EmpSnippetsView.add_link_for_all (/packages/emp-debugger/lib/debugger/emp_debugger_snippets_view.coffee:34:18)
    at /packages/emp-debugger/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/emp-debugger/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/emp-debugger/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -0:47.7.0 emp-debugger:setting-view (atom-pane.pane.active)
```

### Non-Core Packages

```
emp-debugger 0.11.1 
simplified-chinese-menu 5.3.5 
```

**Comment by jcrom** [comment]
这个问题我暂时复现不出来, 能具体的说说复现步骤吗?
